//Nombre bbdd
spring.datasource.url=jdbc:mysql://localhost:3306/bodega
spring.datasource.username=root
spring.datasource.password=20042023

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=T9t9b2F1Lksndf983nDlmf9JQlznbmRZkLmASR3kLxE=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=andybercich6@gmail.com
spring.mail.password=ogrgivtovssbuoxn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true